Repository jenkinsci/parameterized-trigger-plugin, pull requests merged in 2019-12, with the labels that each got.

#124 [JENKINS-57472] Keep node label even if machine disconnects
  src/main/java/hudson/plugins/parameterizedtrigger/NodeParameters.java
Labels: bug

#132 Enable Release Drafter in the repository
  .github/release-drafter.yml
Labels: chore

#133 Use GitHub as a source of documentation on plugins.jenkins.io
  pom.xml
Labels: documentation

#134 Add plugin badges and reference the security advisory in the parameters passing warning
  README.md
Labels: documentation

#137 Use GitHub actions to generate release drafts
  .github/workflows/changelog.yml
Labels: chore

#136 Cleanup obsolete maintainer INFO
  pom.xml
Labels: chore
