Repository jenkinsci/parameterized-trigger-plugin, pull requests merged in 2023-11, with the labels that each got.

#364 Fix javadoc warning
  src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
Labels: documentation

#365 Remove redundant spotbugs setting
  pom.xml
Labels: chore

#363 Cancel pending triggered build when parent project is cancelled
  src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
  src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
Labels: enhancement

#357 JENKINS-71919 Use modern icon class in subproject page
  src/main/resources/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction/summary.groovy
Labels: bug

#366 Enable continuous delivery
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore
