Repository jenkinsci/parameterized-trigger-plugin, pull requests merged in 2024-05, with the labels that each got.

#378 Bump promoted-builds optional dependency to 892.vd6219fc0a_efb
  .github/dependabot.yml
  pom.xml
Labels: chore

#375 Do not warn when triggered job is a success
  src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
Labels: bug

#381 Fix javadoc warnings
  src/main/java/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction.java
  src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
  src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
Labels: documentation

#383 Remove System V init instructions that no longer work
  CHANGELOG.md
  README.md
  src/main/resources/hudson/plugins/parameterizedtrigger/CounterBuildParameterFactory/help-validationFail.html
  src/main/resources/hudson/plugins/parameterizedtrigger/FileBuildParameterFactory/help-noFilesFoundAction.html
  src/main/resources/hudson/plugins/parameterizedtrigger/SubversionRevisionBuildParameters/config.jelly
Labels: documentation
